version: "3.4"

services:

  web.apigateway:
    image: ${DOCKER_REGISTRY-}webapigateway
    build:
      context: .
      dockerfile: src/AppGateways/Web.ApiGateway/Dockerfile

  favoriteservice:
    image: ${DOCKER_REGISTRY-}favoriteservice
    build:
      context: .
      dockerfile: src/Services/FavoriteService/FavoriteService/Dockerfile

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: src/Services/IdentityService/IdentityService/Dockerfile

  pageservice:
    image: ${DOCKER_REGISTRY-}pageservice
    build:
      context: .
      dockerfile: src/Services/PageService/PageService/Dockerfile

  sitemapservice:
    image: ${DOCKER_REGISTRY-}sitemapservice
    build:
      context: .
      dockerfile: src/Services/SiteMapService/SiteMapService/Dockerfile

  s_redis:
    container_name: c_redis
    image: redis

  s_rabbitmq:
    container_name: c_rabbitmq
    image: rabbitmq:3-management

  s_sqlserver:
    container_name: c_sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest

  s_consul:
    container_name: c_consul
    image: consul

  s_mongo-express:
    container_name: s_mongo-express
    image: mongo-express

  s_mongo:
    container_name: s_mongo
    image: mongo

  s_nginx:
    container_name: c_nginx
    image: nginx

  s_elasticsearch:
    container_name: s_elasticsearch
    image: elasticsearch
  s_kibana:
    container_name: s_kibana
    image: kibana
  s_graylog:
    container_name: s_graylog
    image: graylog

  webapp:
    container_name: webapp
    image: webapp
    build:
      context: .
      dockerfile: src/Clients/AngularWebApp/WebApp/Dockerfile
