version: '3.4'

services:
  web.apigateway:
    container_name: web.apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:2000
      - ConsulConfig__Address=http://s_consul:8500
      - ConsulConfig__ServiceAddress=http://web.apigateway:2000
      - ConsulConfig__ServiceName=web.apigateway
      - ConsulConfig__ServiceId=web.apigateway
    ports:
      - "2000:2000"
    depends_on:
      - s_sqlserver
      - s_consul
      - s_rabbitmq
    networks:
      - net_backendservices

  favoriteservice:
    container_name: favoriteservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ConsulConfig__Address=http://s_consul:8500
      - ConsulConfig__ServiceAddress=http://favoriteservice:5001
      - ConsulConfig__ServiceName=favoriteservice
      - ConsulConfig__ServiceId=favoriteservice
    ports:
      - "5001:5001"
    depends_on:
      - s_sqlserver
      - s_consul
      - s_rabbitmq
      - web.apigateway
    networks:
      - net_backendservices

  identityservice:
    container_name: identityservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3000
      - ConsulConfig__Address=http://s_consul:8500
      - ConsulConfig__ServiceAddress=http://identityservice:3000
      - ConsulConfig__ServiceName=identityservice
      - ConsulConfig__ServiceId=identityservice
    ports:
      - "3000:3000"
    depends_on:
      - s_sqlserver
      - s_consul
      - s_rabbitmq
      - web.apigateway
    networks:
      - net_backendservices


  pageservice:
    container_name: pageservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - ConsulConfig__Address=http://s_consul:8500
      - ConsulConfig__ServiceAddress=http://pageservice:5002
      - ConsulConfig__ServiceName=pageservice
      - ConsulConfig__ServiceId=pageservice
    ports:
      - "5002:5002"
    depends_on:
      - s_sqlserver
      - s_consul
      - s_rabbitmq
      - web.apigateway
    networks:
      - net_backendservices

  s_consul:
    ports:
       - 8500:8500
       - 8600:8600/tcp
       - 8600:8600/udp
    networks:
       - net_frontend
       - net_backendservices    

  s_rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - net_backendservices
      - net_frontend
   
  s_redis:
    ports: 
    - 6379:6379
    volumes:
    - /opt/app_data/redis/:/data
    networks:
    - net_backendservices

  s_sqlserver:
    user: root
    ports:
     - 1433:1433
    environment:
    - ACCEPT_EULA=sa
    - MSSQL_SA_PASSWORD=semihO123.
    volumes:
     - sqlserver_data:/var/opt/mssql/data
     - sqlserver_log:/var/opt/mssql/log
    networks:
     - net_backendservices

networks:
  net_frontend:
    driver: bridge
    external: true
  net_backendservices:
    driver: bridge
    external: true
    
        
volumes:
  rabbitmq:
  sqlserver_data:
  sqlserver_log: